use gdbgames;
-- Inserimento dei clienti
INSERT INTO cliente (email, nome, cognome, pw, via, civico, città, provincia, cap, stato) 
VALUES
('mariorossi@email.com', 'Mario', 'Rossi', SHA2('1234',512), 'Via Roma', 123, 'Milano', 'MI', 20100, 'utente'),
('luigiverdi@email.com', 'Luigi', 'Verdi', SHA2('1234',512), 'Via Roma', 23, 'Caserta', 'CE', 81100, 'utente'),
('peppeneri@email.com', 'Peppe', 'Neri', SHA2('1234',512), 'Corso Trieste', 12, 'Caserta', 'CE', 81100, 'utente'),
('admin@email.com', 'pippo', 'admin', SHA2('admin',512), 'Via Napoli', 10, 'Napoli', 'NA', 34102, 'admin');


-- Inserimento degli acquisti
INSERT INTO acquisto (emailCliente, ncarta, nFattura, dataAcquisto, via, cap, città, prezzoTotale) VALUES
('mariorossi@email.com', 12345678, 1, '2024-05-28', 'Via Roma', 20100, 'Milano', 100.50),
('luigiverdi@email.com', 12445798, 2, '2024-02-10', 'Via Acquaviva', 81100, 'Caserta', 200.50),
('peppeneri@email.com', 11345655, 3,  '2023-12-18', 'Via Roma', 81100, 'Caserta', 500.50);

-- Inserimento dei generi
INSERT INTO genere (nome) 
VALUES 
    ( 'Avventura Storica'),
    ( 'Avventura Epica'),
    ( 'Sparatutto in Prima Persona'),
    ( 'Azione Open-World'),
    ( 'Simulazione di Calcio'),
    ( 'Simulazione di Vita'),
    ( 'Avventura Post-Apocalittica'),
    ( 'Sparatutto Tattico'),
    ( 'Azione e Avventura'),
    ( 'Platformer'),
    ( 'GDR Epico'),
    ( 'Corse'),
    ( 'Avventura Open-World');

-- Inserimento delle console
INSERT INTO console (nome) 
VALUES 
('Ps4'),
('Xbox'),
('Switch'),
('PC');

-- Inserimento dei videogiochi
INSERT INTO videogioco (img, titolo, descrizione, pegi) 
VALUES
(null, 'Sea of Thieves', 'Sea of Thieves è un gioco di avventura multigiocatore sviluppato da Rare e pubblicato da Xbox Game Studios. Ambientato in un mondo piratesco, i giocatori assumono il ruolo di pirati e navigano per mari aperti, completando missioni, cercando tesori nascosti e affrontando altre navi pirata. Il gioco enfatizza la cooperazione tra giocatori, permettendo ai gruppi di amici di formare ciurme e lavorare insieme per esplorare isole, combattere creature mitiche e difendere il proprio bottino.', 12),
(null, 'Assassin''s Creed 3', 'Assassin\'s Creed 3 è un gioco di avventura storica che ti porta nel cuore della Rivoluzione Americana. Nei panni di Connor, un assassino nativo americano, combatti per la libertà del tuo popolo e per la giustizia. Esplora un mondo ricco di dettagli storici accurati e vivi una trama coinvolgente che intreccia eventi storici e finzione.', 18),
(null, 'Assassin''s Creed Valhalla', 'Assassin\'s Creed Valhalla è un\'epica avventura vichinga che ti porta nelle terre selvagge dell\'Inghilterra medievale. Guida Eivor, un temibile guerriero vichingo, attraverso battaglie sanguinose, alleanze politiche e misteri ancestrali. Il gioco offre un vasto open-world da esplorare, con numerose attività e missioni secondarie.', 18),
(null, 'Call of Duty: Modern Warfare', 'Call of Duty: Modern Warfare è un intenso sparatutto in prima persona che ti immerge in una trama realistica e coinvolgente. Combatti in scenari dettagliati e realistici, affrontando minacce globali e terrorismo. Il gioco offre una campagna ricca di azione, modalità multiplayer competitive e operazioni speciali cooperative.', 18),
(null, 'Far Cry 3', 'Far Cry 3 è un\'avventura open-world ambientata su un\'isola tropicale paradisiaca ma pericolosa. Esplora l\'isola, sopravvivi ai suoi pericoli e affronta nemici spietati per salvare i tuoi amici. Il gioco combina elementi di sparatutto in prima persona con esplorazione e sopravvivenza.', 18),
(null, 'Far Cry 6', 'Far Cry 6 è un\'avventura open-world ambientata in Yara, un\'immaginaria isola caraibica. Lotta contro il dittatore Anton Castillo e i suoi sostenitori per liberare l\'isola e il suo popolo. Il gioco offre un vasto mondo aperto, missioni dinamiche e un arsenale di armi e veicoli.', 18),
(null, 'FIFA 23', 'FIFA 23 è la simulazione di calcio definitiva con squadre e giocatori reali. Vivi l\'emozione del calcio, gestisci la tua squadra e competi in tornei internazionali. Il gioco offre modalità di gioco variegate, inclusi carriera, ultimate team e competizioni online.', 3),
(null, 'GTA 5', 'GTA 5 è un\'avventura open-world piena di azione, crimini e veicoli. Esplora la vasta città di Los Santos, commetti crimini audaci e costruisci il tuo impero criminale. Il gioco offre una campagna ricca di storie intrecciate e un mondo online dinamico con missioni cooperative e competitive.', 18),
(null, 'Horizon Forbidden West', 'Horizon Forbidden West è un\'avventura post-apocalittica in un mondo dominato da creature robotiche. Esplora le rovine dell\'America, scopri segreti antichi e lotta per la sopravvivenza. Il gioco offre un vasto mondo aperto, combattimenti intensi e una trama avvincente.', 18),
(null, 'Rainbow Six Siege', 'Rainbow Six Siege è un intenso sparatutto tattico in squadra. Scegli tra una varietà di operatori speciali, costruisci difese, pianifica strategie e lavora in squadra per la vittoria. Il gioco offre modalità multiplayer competitive e aggiornamenti costanti con nuovi contenuti.', 18),
(null, 'Sekiro: Shadows Die Twice', 'Sekiro: Shadows Die Twice è un\'avventura d\'azione ambientata nel Giappone feudale. Affronta nemici letali, scopri segreti oscuri e lotta per la tua sopravvivenza in un mondo brutale e bellissimo. Il gioco offre combattimenti impegnativi e una trama coinvolgente.', 18),
(null, 'Super Mario Odyssey', 'Super Mario Odyssey è un divertente platformer con il famoso Mario. Esplora mondi fantastici, raccogli lune per alimentare il tuo vascello e salva la principessa Peach dalle grinfie di Bowser. Il gioco offre una varietà di ambientazioni creative e sfide uniche.', 3),
(null, 'The Witcher 3: Wild Hunt', 'The Witcher 3: Wild Hunt è un GDR epico che ti mette nei panni di Geralt, un cacciatore di mostri. Esplora un mondo vasto e affascinante, affronta creature leggendarie e prendi decisioni che influenzano il corso della storia. Il gioco offre una trama complessa, missioni secondarie ricche di dettagli e un sistema di combattimento avanzato.', 18),
(null, 'The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Breath of the Wild è un\'avventura open-world con Link. Esplora il vasto regno di Hyrule, risolvi enigmi complessi, sconfiggi nemici e salva la principessa Zelda. Il gioco offre un mondo aperto ricco di segreti e una libertà di esplorazione senza precedenti.', 12),
(null, 'Donkey Kong Country: Tropical Freeze', 'Donkey Kong Country: Tropical Freeze è un platform sviluppato da Retro Studios e pubblicato da Nintendo. Segui Donkey Kong e i suoi amici mentre cercano di salvare la loro isola dai nevosi invasori dei Vichinghi. Il gioco offre livelli impegnativi, boss memorabili e una grafica vivace.', 3),
(null, 'Hollow Knight', 'Hollow Knight è un gioco di avventura e azione in stile Metroidvania sviluppato da Team Cherry. Esplora il vasto e intricato regno di Hallownest, combattendo nemici e scoprendo segreti. Il gioco offre una grafica disegnata a mano, un gameplay impegnativo e una trama avvincente.', 7),
(null, 'Luigi\'s Mansion 3', 'Luigi\'s Mansion 3 è un gioco di azione e avventura sviluppato da Next Level Games e pubblicato da Nintendo. Accompagna Luigi mentre esplora un hotel infestato per salvare i suoi amici dalle grinfie dei fantasmi. Il gioco offre enigmi ingegnosi, battaglie contro boss e un divertente multiplayer.', 7),
(null, 'Mario Kart 8 Deluxe', 'Mario Kart 8 Deluxe è un gioco di corse sviluppato e pubblicato da Nintendo. Il gioco offre una vasta gamma di personaggi e piste colorate, con modalità multiplayer sia online che offline. Competi in emozionanti gare di kart, utilizzando oggetti e power-up per superare i tuoi avversari.', 3),
(null, 'Splatoon 2', 'Splatoon 2 è uno sparatutto in terza persona sviluppato e pubblicato da Nintendo. Partecipa a battaglie multiplayer a base di vernice, completando missioni e sfide in un colorato mondo post-apocalittico. Il gioco offre modalità competitive e cooperative, eventi stagionali e aggiornamenti costanti.', 7),
(null, 'Animal Crossing: New Horizons', 'Animal Crossing: New Horizons è un gioco di simulazione sviluppato e pubblicato da Nintendo. Crea e gestisci la tua isola deserta, interagisci con i residenti e personalizza il tuo paradiso personale. Il gioco offre un\'esperienza rilassante con numerose attività, eventi stagionali e un alto grado di personalizzazione.', 3);


-- Inserimento delle distinzioni (associazione tra videogiochi e generi)
INSERT INTO distinzione (titoloVideogioco, nomeGenere) 
VALUES 
    ('Assassin''s Creed 3', 'Avventura Storica'),
    ('Assassin''s Creed Valhalla', 'Avventura Epica'),
    ('Call of Duty: Modern Warfare', 'Sparatutto in Prima Persona'),
    ('Far Cry 3', 'Azione Open-World'),
    ('Far Cry 6', 'Azione Open-World'),
    ('FIFA 23', 'Simulazione di Calcio'),
    ('GTA 5', 'Azione Open-World'),
    ('Horizon Forbidden West', 'Avventura Post-Apocalittica'),
    ('Rainbow Six Siege', 'Sparatutto Tattico'),
    ('Sekiro: Shadows Die Twice', 'Azione e Avventura'),
    ('Super Mario Odyssey', 'Platformer'),
    ('The Witcher 3: Wild Hunt', 'GDR Epico'),
    ('The Legend of Zelda: Breath of the Wild', 'Avventura Open-World'),
	('Sea of Thieves', 'Azione e Avventura'),
    ('Donkey Kong Country: Tropical Freeze', 'Platformer'),
	('Hollow Knight', 'Azione e Avventura'),
	('Mario Kart 8 Deluxe', 'Corse'),
	('Luigi\'s Mansion 3', 'Azione e Avventura'),
	('Splatoon 2', 'Sparatutto in Prima Persona'),
	('Animal Crossing: New Horizons', 'Simulazione di Vita');

-- Inserimento delle copie
INSERT INTO copia (stato, percIva, prezzo, codiceAcquisto, titoloVideogioco, nomeConsole) 
VALUES 
(true, 22.0, 49.99, 1, 'GTA 5', 'Ps4'),
(true, 22.0, 59.99, 1, 'Assassin''s Creed 3', 'Ps4'),
(true, 22.0, 39.99, 1, 'FIFA 23', 'Ps4'),
(true, 22.0, 49.99, 2, 'Far Cry 6', 'Xbox'),
(true, 22.0, 59.99, 2, 'Call of Duty: Modern Warfare', 'Xbox'),
(true, 22.0, 39.99, 2, 'Rainbow Six Siege', 'Xbox'),
(true, 22.0, 49.99, 3, 'The Legend of Zelda: Breath of the Wild', 'Switch'),
(true, 22.0, 59.99, 3, 'Super Mario Odyssey', 'Switch'),
(true, 22.0, 39.99, 3, 'Horizon Forbidden West', 'Switch'),
('false', 22.0, 59.99, NULL, 'Sea of Thieves', 'Xbox'),
('false', 22.0, 59.99, NULL, 'Sea of Thieves', 'Xbox'),
('false', 22.0, 59.99, NULL, 'Sea of Thieves', 'Xbox'),
('false', 22.0, 59.99, NULL, 'Sea of Thieves', 'Xbox'),
('false', 22.0, 59.99, NULL, 'Sea of Thieves', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Far Cry 6', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Far Cry 6', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Far Cry 6', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Far Cry 6', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Far Cry 6', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'Xbox'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'Ps4'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'Ps4'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Ps4'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Ps4'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Xbox'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Xbox'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Xbox'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Xbox'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Xbox'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Xbox'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Switch'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Switch'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Switch'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'Switch'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'Switch'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'Switch'),
(false, 22.0, 59.99, NULL, 'FIFA 23', 'Switch'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'Xbox'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'Xbox'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 49.99, NULL, 'GTA 5', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'Xbox'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 59.99, NULL, 'Assassin''s Creed Valhalla', 'PC'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'Xbox'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'PC'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'PC'),
(false, 22.0, 39.99, NULL, 'Far Cry 3', 'PC'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'PC'),
(false, 22.0, 49.99, NULL, 'Sekiro: Shadows Die Twice', 'PC'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'Ps4'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'PC'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'PC'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'PC'),
(false, 22.0, 59.99, NULL, 'The Witcher 3: Wild Hunt', 'PC'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Ps4'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Ps4'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'Ps4'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'PC'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'PC'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'PC'),
(false, 22.0, 39.99, NULL, 'The Legend of Zelda: Breath of the Wild', 'PC'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'Ps4'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'PC'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'PC'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'PC'),
(false, 22.0, 49.99, NULL, 'Super Mario Odyssey', 'PC'),
(false, 22.0, 59.99, NULL, 'FIFA 23', 'Ps4'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'PC'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'PC'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'PC'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'PC'),
(false, 22.0, 39.99, NULL, 'Rainbow Six Siege', 'PC'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Ps4'),
(false, 22.0, 59.99, NULL, 'Call of Duty: Modern Warfare', 'Ps4'),
(false, 22.0, 59.99, NULL, 'FIFA 23', 'PC'),
(false, 22.0, 49.99, NULL, 'Donkey Kong Country: Tropical Freeze', 'Switch'),
(false, 22.0, 49.99, NULL, 'Donkey Kong Country: Tropical Freeze', 'Switch'),
(false, 22.0, 49.99, NULL, 'Donkey Kong Country: Tropical Freeze', 'Switch'),
(false, 22.0, 49.99, NULL, 'Donkey Kong Country: Tropical Freeze', 'Switch'),
(false, 22.0, 49.99, NULL, 'Donkey Kong Country: Tropical Freeze', 'Switch'),
(false, 22.0, 19.99, NULL, 'Hollow Knight', 'Switch'),
(false, 22.0, 19.99, NULL, 'Hollow Knight', 'Switch'),
(false, 22.0, 19.99, NULL, 'Hollow Knight', 'Switch'),
(false, 22.0, 19.99, NULL, 'Hollow Knight', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 39.99, NULL, 'Mario Kart 8 Deluxe', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Luigi\'s Mansion 3', 'Switch'),
(false, 22.0, 59.99, NULL, 'Splatoon 2', 'Switch'),
(false, 22.0, 59.99, NULL, 'Splatoon 2', 'Switch'),
(false, 22.0, 59.99, NULL, 'Splatoon 2', 'Switch'),
(false, 22.0, 59.99, NULL, 'Splatoon 2', 'Switch'),
(false, 22.0, 59.99, NULL, 'Splatoon 2', 'Switch'),
(false, 22.0, 59.99, NULL, 'Animal Crossing: New Horizons', 'Switch'),
(false, 22.0, 59.99, NULL, 'Animal Crossing: New Horizons', 'Switch'),
(false, 22.0, 59.99, NULL, 'Animal Crossing: New Horizons', 'Switch'),
(false, 22.0, 59.99, NULL, 'Animal Crossing: New Horizons', 'Switch');
  
-- Inserimento dei reclami
INSERT INTO reclamo (dataReclamo, nReclamo, titolo, contenuto, emailCliente) 
VALUES 
('2023-02-10', 1, 'Problema con il download', 'Non riesco a scaricare il gioco acquistato.', 'mariorossi@email.com'),
('2024-08-15', 2, 'Gioco difettoso', 'Il gioco si blocca continuamente durante il caricamento.', 'luigiverdi@email.com'),
('2022-12-18', 3, 'Codice di attivazione non funzionante', 'Il codice di attivazione fornito non funziona.', 'peppeneri@email.com'),
('2024-05-20', 4, 'Consegna in ritardo', 'Il gioco acquistato non Ã¨ ancora stato consegnato nonostante la data di rilascio sia giÃ  passata.', 'mariorossi@email.com'),
('2024-05-25', 5, 'Grafica difettosa', 'La grafica del gioco presenta difetti e glitch che rendono lâ€™esperienza di gioco impossibile.', 'luigiverdi@email.com');
